from __future__ import annotations

from io import BytesIO

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .schemas import AnswerEvaluation, InterviewQuestion, ResumeAnalysis, ResumeProfile


def _safe(value: object) -> str:
    return str(value or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def build_readiness_pdf(resume: ResumeProfile, role: str, company: str, analysis: ResumeAnalysis | None, questions: list[InterviewQuestion], evaluations: list[AnswerEvaluation]) -> bytes:
    buffer = BytesIO()
    document = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=42, leftMargin=42, topMargin=42, bottomMargin=42)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="TitleCenter", parent=styles["Title"], alignment=TA_CENTER, textColor=colors.HexColor("#183B56")))
    styles.add(ParagraphStyle(name="Small", parent=styles["BodyText"], fontSize=8, leading=10, textColor=colors.HexColor("#536471")))
    story = [Paragraph("AI Interview & Resume Prep Report", styles["TitleCenter"]), Spacer(1, 8)]
    story.append(Paragraph(f"<b>Candidate:</b> {_safe(resume.name)} &nbsp;&nbsp; <b>Target:</b> {_safe(role)} at {_safe(company or 'Target company')}", styles["BodyText"]))
    story.append(Spacer(1, 14))
    if analysis:
        story.append(Paragraph("Resume readiness", styles["Heading2"]))
        story.append(Paragraph(f"<b>Fit score:</b> {analysis.fit_score}/100", styles["BodyText"]))
        story.append(Paragraph(_safe(analysis.recruiter_summary), styles["BodyText"]))
        story.append(Spacer(1, 6))
        table_data = [["Strengths", "Priority improvements"], ["\n".join(f"• {x}" for x in analysis.strengths[:6]) or "Not available", "\n".join(f"• {x}" for x in analysis.improvement_plan[:6]) or "Not available"]]
        table = Table(table_data, colWidths=[3.4 * inch, 3.4 * inch])
        table.setStyle(TableStyle([("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E8F1F5")), ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#B8C7D1")), ("VALIGN", (0, 0), (-1, -1), "TOP"), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold")]))
        story.extend([table, Spacer(1, 14)])
    if evaluations:
        avg = round(sum(item.overall_score for item in evaluations) / len(evaluations))
        story.append(Paragraph(f"Interview practice score: {avg}/100 across {len(evaluations)} evaluated answer(s)", styles["Heading2"]))
        for idx, evaluation in enumerate(evaluations, 1):
            story.append(Paragraph(f"<b>Answer {idx}: {evaluation.overall_score}/100</b> — {_safe(evaluation.feedback)}", styles["BodyText"]))
            story.append(Paragraph(f"Improvements: {_safe('; '.join(evaluation.improvements))}", styles["Small"]))
            story.append(Spacer(1, 5))
    if questions:
        story.append(Paragraph("Practice question bank", styles["Heading2"]))
        for idx, question in enumerate(questions, 1):
            story.append(Paragraph(f"{idx}. <b>{_safe(question.question)}</b> ({_safe(question.category)}, {_safe(question.difficulty)})", styles["BodyText"]))
            story.append(Paragraph(f"Answer framework: {_safe(question.answer_framework)}", styles["Small"]))
            story.append(Spacer(1, 4))
    story.append(Spacer(1, 12))
    story.append(Paragraph("Generated by AI Interview & Resume Prep Agent. Use feedback as coaching guidance and verify technical answers independently.", styles["Small"]))
    document.build(story)
    return buffer.getvalue()
