[theme]
base = "light"
primaryColor = "#0B7285"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F8FA"
textColor = "#183B56"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = true
